### ISSUE TITLE
Arguendo?

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#31]
@budparr If someone finds themselves in one particular arguendo, what do you think is the best way for them to get out to see other ones? A link to the other ones or something that says "Past Arguendo Roundtables" on righthand bar?

http://www.international-criminal-justice-today.org/arguendo/question/African-Union-and-international-criminal-justice:-where-does-it-go-from-here/

**Comment by budparr** [comment]
I'll add a link to the bottom of the individual page.

**Comment by kiphale** [comment]
Ok @budparr "on the road" ;)

**Comment by budparr** [comment]
duplicate of #50
