### ISSUE TITLE
Ipsos on cover page

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#35]
@budparr How can we change the individual Ipsos report blurb that comes up on the home page?

**Comment by budparr** [comment]
What exactly do you want to change? Right now it takes an excerpt from the latest posts.

**Comment by kiphale** [comment]
Well, they are the exact same excerpt.

**Comment by budparr** [comment]
That's just content. You can change it here: https://github.com/ABA-Center-for-Human-Rights/international-criminal-justice-today/blob/gh-pages/_posts/2014-12-08-ipsos-data-december-2014.md

**Comment by kiphale** [comment]
Merci!
