### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#36]
@budparr Not priority over other things that have not been touched, but just creating a marker about ICJT homepage redesign that you mentioned to me. I can see some helpful changes.

**Comment by budparr** [comment]
You and I might have varying definitions of the word redesign, can you refresh my memory? I recall a conversation about changing things to accommodate the fact that you weren't going to have very much content, but then discussing that it wouldn't be a good idea to limit your content to only prominent individuals. What else?
