### ISSUE TITLE
Palestine

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#37]
I will add Palestine data today to the spreadsheet to make the 123rd state party. I am actually really proud of this moment. Could be a game changer!

**Comment by budparr** [comment]
Awesome. Let me know when it's updated.

**Comment by kiphale** [comment]
Ok I believe this data for the State Party map is in there.

**Comment by budparr** [comment]
I already migrated the state parties data to the new system, so don't add anything else, just send it to me.

**Comment by kiphale** [comment]
Ok. Only other thing that I did was create a new Palestine Preliminary Examination in the spreadsheet "Palestine II".
