### ISSUE TITLE
Navigating within Arguendo

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#50]
@budparr Once you get into a specific "Arguendo", there is no easy way to navigate to the other Arguendos. To me, it is important that we capture people who are interested in this idea of multiple takes on a given question. 
http://www.international-criminal-justice-today.org/arguendo/question/How-can-the-international-community-best-support-the-need-to-protect-witnesses-in-international-criminal-trials/ 

Maybe an arrow that people can hit that takes them back to here (http://www.international-criminal-justice-today.org/arguendo/ ) that says something like "Back to Arguendo homepage"

**Comment by budparr** [comment]
Duplicate #31

**Comment by budparr** [comment]
actually, leave this one open because it's more descriptive, closing the older one

**Comment by kiphale** [comment]
@budparr Is there anyway to make it more prominent and maybe placed above the column of experts? That is where my eye is drawn, and there is lots of white space there to occupy.

**Comment by budparr** [comment]
I can make it more prominent (bigger), but I think it has to have that tight relationship to arguendo, so should be in the same place.
