### ISSUE TITLE
Arguendo pictures

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/international-criminal-justice-today#51]
http://www.international-criminal-justice-today.org/arguendo/question/How-can-the-international-community-best-support-the-need-to-protect-witnesses-in-international-criminal-trials/ 

@budparr I am sure you are still working on this, but why not mash the three pics into one of those split/collage pictures? Maybe the woman on the top half and the guys splitting the bottom half?

**Comment by budparr** [comment]
You were up late! There's no way to do a collage that would a) show up not looking sloppy, and b) show the images large enough. The solution would be to:

- [ ] Show one image as I have here (this person shows here, but shows last on the question's page
- [ ] Show no image at all
- [ ] List all the images in a row, which would take up a lot of space for one article, but is doable.
